### Send POST request with json body
POST http://localhost:8080/api/core/file/create
Content-Type: application/json

{
  "name": "gil2",
  "text": "text",
  "directory_name": "MYDIR",
  "isDir": false
}

### Send POST request with json body
PUT http://localhost:8080/api/core/file/update?id=3
Content-Type: application/json

[{"op": "replace", "path": "/text", "value": "hro"}]

### Send POST request with json body
GET http://localhost:8080/api/core/file/find-all


### Send POST request with json body
POST http://localhost:8080/api/core/user/signup
Content-Type: application/json

{
  "email": "gil@hro.com",
  "password": "Password123"
}

### Send POST request with body as parameters
POST http://localhost:8080/api/core/login
Content-Type: application/x-www-form-urlencoded

username=gil@hro.com&password=Password123

###
### Send POST request with json body
DELETE http://localhost:8080/api/core/file/delete?id=5
