### Send POST request with json body
POST http://localhost:8080/api/core/file/create
Content-Type: application/json

{
  "name": "gil",
  "text": "text",
  "directory": "root",
  "isDir": false
}

### Send POST request with json body
POST http://localhost:8080/api/core/user/signup
Content-Type: application/json

{
  "email": "gil@hro.com",
  "password": "Password123"
}

### Send POST request with body as parameters
POST http://localhost:8080/api/core/login
Content-Type: application/x-www-form-urlencoded

username=gil@hro.com&password=Password123
